# Generated by Django 5.1.7 on 2025-03-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='College',
            new_name='college',
        ),
    ]
